;
; File generated by cc65 v 2.19 - Git 357f64e4e
;
	.fopt		compiler,"cc65 v 2.19 - Git 357f64e4e"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_timer_start
	.export		_timer_stop
	.export		_timer_read
	.export		_timer_is_running
	.export		_timer_cpu_speed
	.export		_timer_ticks_to_us
	.export		_timer_ticks_to_ms
	.export		_timer_delay_ticks
	.export		_timer_delay_us
	.export		_timer_delay_ms
	.export		_timer_get_frequency_hz
	.export		_timer_get_ticks_per_ms
	.export		_timer_get_ticks_per_us

; ---------------------------------------------------------------
; void __near__ timer_start (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_timer_start: near

.segment	"CODE"

	lda     #$01
	sta     $F020
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ timer_stop (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_timer_stop: near

.segment	"CODE"

	lda     #$00
	sta     $F020
	rts

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ timer_read (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_timer_read: near

.segment	"CODE"

	jsr     decsp2
	lda     $F021
	ldy     #$01
	sta     (c_sp),y
	lda     $F022
	dey
	sta     (c_sp),y
	iny
	lda     (c_sp),y
	pha
	dey
	lda     (c_sp),y
	tax
	pla
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ timer_is_running (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_timer_is_running: near

.segment	"CODE"

	lda     $F020
	ldx     #$00
	and     #$01
	beq     L0005
	lda     #$01
	rts
L0005:	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ timer_cpu_speed (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_timer_cpu_speed: near

.segment	"CODE"

	ldx     #$00
	lda     $F023
	rts

.endproc

; ---------------------------------------------------------------
; unsigned long __near__ timer_ticks_to_us (unsigned int ticks)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_timer_ticks_to_us: near

.segment	"CODE"

	jsr     pushax
	jsr     _timer_cpu_speed
	jsr     pusha
	ldy     #$02
	jsr     ldaxysp
	jsr     axulong
	jsr     pusheax
	ldy     #$04
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     tosudiveax
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ timer_ticks_to_ms (unsigned int ticks)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_timer_ticks_to_ms: near

.segment	"CODE"

	jsr     pushax
	jsr     _timer_cpu_speed
	jsr     pusha
	ldx     #$00
	lda     (c_sp,x)
	jsr     axulong
	jsr     pusheax
	lda     #$E8
	ldx     #$03
	jsr     tosumul0ax
	jsr     pusheax
	ldy     #$08
	jsr     pushwysp
	ldy     #$05
	jsr     ldeaxysp
	jsr     tosulong
	jsr     tosudiveax
	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; void __near__ timer_delay_ticks (unsigned int ticks)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_timer_delay_ticks: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp4
	jsr     _timer_start
	ldx     #$00
	txa
	ldy     #$02
	jsr     staxysp
L0002:	jsr     _timer_read
	jsr     stax0sp
	ldy     #$04
	cmp     (c_sp),y
	txa
	iny
	sbc     (c_sp),y
	bcc     L0002
	jsr     _timer_stop
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; void __near__ timer_delay_us (unsigned int microseconds)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_timer_delay_us: near

.segment	"CODE"

	jsr     pushax
	ldy     #$11
	jsr     subysp
	jsr     _timer_cpu_speed
	ldy     #$10
	sta     (c_sp),y
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	ldy     #$0C
	jsr     steaxysp
	ldy     #$0F
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$16
	jsr     ldaxysp
	jsr     axulong
	jsr     tosumuleax
	ldy     #$08
	jsr     steaxysp
	ldy     #$0B
	jsr     ldeaxysp
	cmp     #$00
	txa
	sbc     #$00
	lda     sreg
	sbc     #$01
	lda     sreg+1
	sbc     #$00
	bcc     L0002
	ldy     #$14
	jsr     pushwysp
	ldx     #$03
	lda     #$E8
	jsr     tosudivax
	ldy     #$06
	jsr     staxysp
	ldy     #$14
	jsr     pushwysp
	ldx     #$03
	lda     #$E8
	jsr     tosumodax
	ldy     #$04
	jsr     staxysp
	ldy     #$06
	lda     (c_sp),y
	iny
	ora     (c_sp),y
	beq     L0003
	jsr     ldaxysp
	jsr     _timer_delay_ms
L0003:	ldy     #$04
	lda     (c_sp),y
	iny
	ora     (c_sp),y
	beq     L0008
	ldy     #$0F
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$09
	jsr     ldaxysp
	jsr     axulong
	jsr     tosumuleax
	jsr     steax0sp
	jsr     ldeax0sp
	cmp     #$00
	txa
	sbc     #$00
	lda     sreg
	sbc     #$01
	lda     sreg+1
	sbc     #$00
	bcs     L0008
	ldy     #$01
	jmp     L000A
L0002:	ldy     #$09
L000A:	jsr     ldaxysp
	jsr     _timer_delay_ticks
L0008:	ldy     #$13
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ timer_delay_ms (unsigned int milliseconds)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_timer_delay_ms: near

.segment	"CODE"

	jsr     pushax
	ldy     #$0B
	jsr     subysp
	jsr     _timer_cpu_speed
	ldy     #$0A
	sta     (c_sp),y
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	lda     #$E8
	ldx     #$03
	jsr     tosumul0ax
	ldy     #$06
	jsr     steaxysp
	ldy     #$09
	jsr     ldeaxysp
	jsr     pusheax
	ldx     #$02
	lda     #$4E
	jsr     pushax
	ldy     #$10
	lda     (c_sp),y
	jsr     tosdiva0
	jsr     axlong
	jsr     tossubeax
	ldy     #$02
	jsr     steaxysp
	ldx     #$00
	txa
	jsr     stax0sp
L0002:	jsr     ldax0sp
	ldy     #$0B
	cmp     (c_sp),y
	txa
	iny
	sbc     (c_sp),y
	bcs     L0003
	ldy     #$03
	jsr     ldaxysp
	jsr     _timer_delay_ticks
	ldx     #$00
	lda     #$01
	jsr     addeq0sp
	jmp     L0002
L0003:	iny
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned long __near__ timer_get_frequency_hz (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_timer_get_frequency_hz: near

.segment	"CODE"

	jsr     _timer_cpu_speed
	jsr     pusha
	ldx     #$00
	lda     (c_sp,x)
	jsr     axulong
	jsr     pusheax
	stx     sreg+1
	lda     #$0F
	sta     sreg
	lda     #$40
	ldx     #$42
	jsr     tosumuleax
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned long __near__ timer_get_ticks_per_ms (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_timer_get_ticks_per_ms: near

.segment	"CODE"

	jsr     _timer_cpu_speed
	jsr     pusha
	ldx     #$00
	lda     (c_sp,x)
	jsr     axulong
	jsr     pusheax
	lda     #$E8
	ldx     #$03
	jsr     tosumul0ax
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ timer_get_ticks_per_us (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_timer_get_ticks_per_us: near

.segment	"CODE"

	jmp     _timer_cpu_speed

.endproc

