;
; File generated by cc65 v 2.19 - Git 357f64e4e
;
	.fopt		compiler,"cc65 v 2.19 - Git 357f64e4e"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_spi_init
	.import		_spi_cs_low
	.import		_spi_cs_high
	.import		_spi_set_frequency_khz
	.import		_spi_transfer
	.export		_sd_cmd
	.export		_sd_read
	.export		_sd_write
	.export		_sd_init
	.export		_sd_type
	.export		_sd_error_string
	.import		_timer_delay_ms
	.export		_sdcard_type
	.export		_sd_crc7_byte
	.export		_sd_power_up
	.export		_sd_go_idle_state
	.export		_sd_send_if_cond
	.export		_sd_read_ocr
	.export		_sd_send_app
	.export		_sd_send_op_cond
	.export		_sd_set_blocklen

.segment	"RODATA"

S0009:
	.byte	$43,$4D,$44,$32,$34,$20,$20,$2F,$20,$57,$52,$49,$54,$45,$5F,$53
	.byte	$49,$47,$4E,$4C,$45,$5F,$42,$4C,$4F,$43,$4B,$20,$46,$61,$69,$6C
	.byte	$65,$64,$00
S000D:
	.byte	$43,$4D,$44,$38,$20,$72,$65,$74,$75,$72,$6E,$65,$64,$20,$75,$6E
	.byte	$65,$78,$70,$65,$63,$74,$65,$64,$20,$72,$65,$73,$70,$6F,$6E,$73
	.byte	$65,$00
S0008:
	.byte	$43,$4D,$44,$31,$37,$20,$20,$2F,$20,$52,$45,$41,$44,$5F,$53,$49
	.byte	$4E,$47,$4C,$45,$5F,$42,$4C,$4F,$43,$4B,$20,$46,$61,$69,$6C,$65
	.byte	$64,$00
S000E:
	.byte	$52,$65,$61,$64,$20,$64,$61,$74,$61,$20,$74,$6F,$6B,$65,$6E,$20
	.byte	$74,$69,$6D,$65,$6F,$75,$74,$2F,$65,$72,$72,$6F,$72,$00
S0003:
	.byte	$43,$4D,$44,$30,$20,$20,$20,$2F,$20,$47,$4F,$5F,$49,$44,$4C,$45
	.byte	$5F,$53,$54,$41,$54,$45,$20,$46,$61,$69,$6C,$65,$64,$00
S0007:
	.byte	$41,$43,$4D,$44,$34,$31,$20,$2F,$20,$53,$45,$4E,$44,$5F,$4F,$50
	.byte	$5F,$43,$4F,$4E,$44,$20,$46,$61,$69,$6C,$65,$64,$00
S0004:
	.byte	$43,$4D,$44,$38,$20,$20,$20,$2F,$20,$53,$45,$4E,$44,$5F,$49,$46
	.byte	$5F,$43,$4F,$4E,$44,$20,$46,$61,$69,$6C,$65,$64,$00
S0012:
	.byte	$43,$4D,$44,$31,$33,$20,$28,$52,$45,$41,$44,$5F,$53,$54,$41,$54
	.byte	$55,$53,$29,$20,$66,$61,$69,$6C,$65,$64,$00
S000B:
	.byte	$76,$31,$2E,$30,$20,$73,$64,$63,$61,$72,$64,$20,$6E,$6F,$74,$20
	.byte	$73,$75,$70,$70,$6F,$72,$74,$65,$64,$00
S0013:
	.byte	$73,$64,$63,$61,$72,$64,$20,$69,$73,$20,$77,$72,$69,$74,$65,$20
	.byte	$70,$72,$6F,$74,$65,$63,$74,$65,$64,$00
S0006:
	.byte	$43,$4D,$44,$35,$38,$20,$20,$2F,$20,$52,$45,$41,$44,$5F,$4F,$43
	.byte	$52,$20,$46,$61,$69,$6C,$65,$64,$00
S0011:
	.byte	$57,$72,$69,$74,$65,$20,$6F,$70,$65,$72,$61,$74,$69,$6F,$6E,$20
	.byte	$74,$69,$6D,$65,$6F,$75,$74,$00
S0005:
	.byte	$43,$4D,$44,$35,$35,$20,$20,$2F,$20,$41,$50,$50,$5F,$43,$4D,$44
	.byte	$20,$46,$61,$69,$6C,$65,$64,$00
S000F:
	.byte	$52,$65,$61,$64,$20,$6F,$70,$65,$72,$61,$74,$69,$6F,$6E,$20,$74
	.byte	$69,$6D,$65,$6F,$75,$74,$00
S0010:
	.byte	$57,$72,$69,$74,$65,$20,$64,$61,$74,$61,$20,$72,$65,$6A,$65,$63
	.byte	$74,$65,$64,$00
S0014:
	.byte	$73,$64,$63,$61,$72,$64,$20,$69,$73,$20,$6C,$6F,$63,$6B,$65,$64
	.byte	$00
S000C:
	.byte	$41,$43,$4D,$44,$34,$31,$20,$74,$69,$6D,$65,$6F,$75,$74,$00
S000A:
	.byte	$43,$4D,$44,$31,$20,$46,$61,$69,$6C,$65,$64,$00
S0001:
	.byte	$53,$75,$63,$63,$65,$73,$73,$00
S0002:
	.byte	$45,$72,$72,$6F,$72,$00

.segment	"BSS"

_sdcard_type:
	.res	1,$00

; ---------------------------------------------------------------
; unsigned char __near__ sd_cmd (unsigned char cmd, unsigned char arg0, unsigned char arg1, unsigned char arg2, unsigned char arg3)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sd_cmd: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp3
	lda     #$00
	jsr     pusha
	ldy     #$08
	lda     (c_sp),y
	ora     #$40
	jsr     _sd_crc7_byte
	ldy     #$02
	sta     (c_sp),y
	ldy     #$07
	lda     (c_sp),y
	ora     #$40
	jsr     _spi_transfer
	ldy     #$02
	lda     (c_sp),y
	jsr     pusha
	ldy     #$07
	lda     (c_sp),y
	jsr     _sd_crc7_byte
	ldy     #$02
	sta     (c_sp),y
	ldy     #$06
	lda     (c_sp),y
	jsr     _spi_transfer
	ldy     #$02
	lda     (c_sp),y
	jsr     pusha
	ldy     #$06
	lda     (c_sp),y
	jsr     _sd_crc7_byte
	ldy     #$02
	sta     (c_sp),y
	ldy     #$05
	lda     (c_sp),y
	jsr     _spi_transfer
	ldy     #$02
	lda     (c_sp),y
	jsr     pusha
	ldy     #$05
	lda     (c_sp),y
	jsr     _sd_crc7_byte
	ldy     #$02
	sta     (c_sp),y
	ldy     #$04
	lda     (c_sp),y
	jsr     _spi_transfer
	ldy     #$02
	lda     (c_sp),y
	jsr     pusha
	ldy     #$04
	lda     (c_sp),y
	jsr     _sd_crc7_byte
	ldy     #$02
	sta     (c_sp),y
	iny
	lda     (c_sp),y
	jsr     _spi_transfer
	ldy     #$02
	lda     (c_sp),y
	asl     a
	ora     #$01
	sta     (c_sp),y
	jsr     _spi_transfer
	lda     #$08
	ldy     #$01
L0008:	sta     (c_sp),y
	ldx     #$00
	lda     (c_sp),y
	beq     L0009
	lda     #$FF
	jsr     _spi_transfer
	ldy     #$00
	sta     (c_sp),y
	and     #$80
	bne     L0004
	tax
	lda     (c_sp),y
	jmp     incsp8
L0004:	iny
	clc
	tya
	adc     (c_sp),y
	jmp     L0008
L0009:	lda     #$FF
	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ sd_read (unsigned long block_num, unsigned char *buffer)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sd_read: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp7
	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_low
	lda     #$FF
	jsr     _spi_transfer
	lda     _sdcard_type
	cmp     #$03
	beq     L0010
	ldy     #$0C
	jsr     ldeaxysp
	ldy     sreg
	sty     sreg+1
	stx     sreg
	tax
	lda     #$00
	jsr     shleax1
	ldy     #$09
	jsr     steaxysp
L0010:	lda     #$11
	jsr     pusha
	ldy     #$0D
	jsr     ldeaxysp
	lda     sreg+1
	jsr     pusha
	ldy     #$0E
	jsr     ldeaxysp
	lda     sreg
	jsr     pusha
	ldy     #$0F
	jsr     ldeaxysp
	txa
	jsr     pusha
	ldy     #$0D
	lda     (c_sp),y
	jsr     _sd_cmd
	cmp     #$00
	beq     L0003
	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_high
	lda     #$FF
	jsr     _spi_transfer
	ldx     #$00
	lda     #$07
	jmp     L0001
L0003:	ldx     #$13
	lda     #$88
	ldy     #$02
	jsr     staxysp
L0004:	ldy     #$02
	lda     (c_sp),y
	iny
	ora     (c_sp),y
	jeq     L0005
	lda     #$FF
	jsr     _spi_transfer
	ldy     #$06
	sta     (c_sp),y
	cmp     #$FE
	bne     L0011
	ldx     #$00
	txa
	ldy     #$04
	jsr     staxysp
L000A:	ldy     #$05
	jsr     ldaxysp
	cpx     #$02
	bcs     L000B
	ldy     #$05
	jsr     ldaxysp
	clc
	ldy     #$07
	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	jsr     pushax
	lda     #$FF
	jsr     _spi_transfer
	ldy     #$00
	jsr     staspidx
	ldy     #$04
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L000A
L000B:	lda     #$FF
	jsr     _spi_transfer
	ldy     #$01
	sta     (c_sp),y
	lda     #$FF
	jsr     _spi_transfer
	ldy     #$00
	sta     (c_sp),y
	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_high
	lda     #$FF
	jsr     _spi_transfer
	ldx     #$00
	txa
	jmp     L0001
L0011:	ldx     #$00
	lda     (c_sp),y
	cmp     #$FF
	beq     L0012
	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_high
	lda     #$FF
	jsr     _spi_transfer
	ldx     #$00
	lda     #$21
	jmp     L0001
L0012:	lda     #$01
	ldy     #$02
	jsr     subeqysp
	jmp     L0004
L0005:	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_high
	lda     #$FF
	jsr     _spi_transfer
	ldx     #$00
	lda     #$22
L0001:	ldy     #$0D
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ sd_write (unsigned long block_num, unsigned char *buffer)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sd_write: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp6
	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_low
	lda     #$FF
	jsr     _spi_transfer
	lda     #$0D
	jsr     pusha
	lda     #$00
	jsr     pusha
	jsr     pusha
	jsr     pusha
	jsr     _sd_cmd
	cmp     #$00
	bne     L0004
	lda     #$FF
	jsr     _spi_transfer
	cmp     #$00
	beq     L0004
	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_high
	lda     #$FF
	jsr     _spi_transfer
	ldx     #$00
	lda     #$40
	jmp     L0001
L0004:	lda     _sdcard_type
	cmp     #$03
	beq     L0015
	ldy     #$0B
	jsr     ldeaxysp
	ldy     sreg
	sty     sreg+1
	stx     sreg
	tax
	lda     #$00
	jsr     shleax1
	ldy     #$08
	jsr     steaxysp
L0015:	lda     #$18
	jsr     pusha
	ldy     #$0C
	jsr     ldeaxysp
	lda     sreg+1
	jsr     pusha
	ldy     #$0D
	jsr     ldeaxysp
	lda     sreg
	jsr     pusha
	ldy     #$0E
	jsr     ldeaxysp
	txa
	jsr     pusha
	ldy     #$0C
	lda     (c_sp),y
	jsr     _sd_cmd
	cmp     #$00
	beq     L0008
	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_high
	lda     #$FF
	jsr     _spi_transfer
	ldx     #$00
	lda     #$08
	jmp     L0001
L0008:	lda     #$FE
	jsr     _spi_transfer
	ldx     #$00
	txa
	ldy     #$03
	jsr     staxysp
L0009:	ldy     #$04
	jsr     ldaxysp
	cpx     #$02
	bcs     L000A
	ldy     #$04
	jsr     ldaxysp
	clc
	ldy     #$06
	adc     (c_sp),y
	sta     ptr1
	txa
	iny
	adc     (c_sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     _spi_transfer
	ldy     #$03
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0009
L000A:	lda     #$FF
	jsr     _spi_transfer
	lda     #$FF
	jsr     _spi_transfer
	lda     #$FF
	jsr     _spi_transfer
	ldy     #$05
	sta     (c_sp),y
	ldx     #$00
	and     #$1F
	cmp     #$05
	beq     L0016
	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_high
	lda     #$FF
	jsr     _spi_transfer
	ldx     #$00
	lda     #$31
	jmp     L0001
L0016:	txa
	jsr     stax0sp
	jmp     L0011
L000F:	lda     #$FF
	jsr     _spi_transfer
	ldy     #$02
	sta     (c_sp),y
	lda     (c_sp),y
	bne     L0010
	tax
	lda     #$01
	jsr     addeq0sp
L0011:	ldy     #$01
	lda     (c_sp),y
	cmp     #$FD
	bne     L0012
	dey
	lda     (c_sp),y
	cmp     #$E8
L0012:	bcc     L000F
L0010:	jsr     ldax0sp
	cmp     #$E8
	txa
	sbc     #$FD
	bcc     L0017
	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_high
	lda     #$FF
	jsr     _spi_transfer
	ldx     #$00
	lda     #$32
	jmp     L0001
L0017:	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_high
	lda     #$FF
	jsr     _spi_transfer
	ldx     #$00
	txa
L0001:	ldy     #$0C
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ sd_init (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sd_init: near

.segment	"CODE"

	ldy     #$0E
	jsr     subysp
	ldx     #$00
	txa
	ldy     #$0D
	sta     (c_sp),y
	jmp     L0038
L0005:	ldy     #$0D
L0043:	ldx     #$00
L0038:	lda     (c_sp),y
	beq     L0008
	cmp     #$01
	beq     L0039
	cmp     #$02
	jeq     L003A
	cmp     #$03
	jeq     L0021
	cmp     #$04
	jeq     L0027
	cmp     #$05
	jeq     L002D
	cmp     #$06
	jeq     L0033
	cmp     #$07
	jeq     L0036
	jmp     L0038
L0008:	jsr     _sd_power_up
	ldx     #$00
	lda     #$32
	jsr     _timer_delay_ms
	ldx     #$00
	lda     #$01
	ldy     #$0D
	sta     (c_sp),y
	jmp     L0038
L0039:	lda     #$00
	ldy     #$0B
	jsr     staxysp
L000A:	ldy     #$0C
	jsr     ldaxysp
	cmp     #$0A
	txa
	sbc     #$00
	bvc     L000E
	eor     #$80
L000E:	bpl     L000B
	jsr     _sd_go_idle_state
	cmp     #$01
	bne     L000C
	lda     #$02
	ldy     #$0D
	sta     (c_sp),y
	jmp     L000B
L000C:	ldy     #$0B
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L000A
L000B:	ldy     #$0C
	jsr     ldaxysp
	cmp     #$0A
	txa
	sbc     #$00
	bvs     L0011
	eor     #$80
L0011:	jpl     L0005
	ldx     #$00
	lda     #$02
	jmp     L0003
L003A:	lda     #$00
	ldy     #$0B
	jsr     staxysp
L0013:	ldy     #$0C
	jsr     ldaxysp
	cmp     #$0A
	txa
	sbc     #$00
	bvc     L0017
	eor     #$80
L0017:	bpl     L0014
	lda     #$04
	jsr     leaa0sp
	jsr     _sd_send_if_cond
	ldy     #$08
	sta     (c_sp),y
	cmp     #$01
	bne     L003E
	dey
	lda     (c_sp),y
	cmp     #$AA
	bne     L003B
	dey
	lda     (c_sp),y
	and     #$01
	bne     L003C
L003B:	ldx     #$00
	lda     #$03
	jmp     L0003
L003C:	lda     #$01
	sta     _sdcard_type
	lda     #$04
	ldy     #$0D
	sta     (c_sp),y
	jmp     L0014
L003E:	lda     (c_sp),y
	cmp     #$05
	bne     L0015
	lda     #$00
	sta     _sdcard_type
	lda     #$04
	ldy     #$0D
	sta     (c_sp),y
	jmp     L0014
L0015:	ldy     #$0B
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0013
L0014:	ldy     #$0C
	jsr     ldaxysp
	cmp     #$0A
	txa
	sbc     #$00
	bvs     L0020
	eor     #$80
L0020:	jpl     L0005
	ldx     #$00
	lda     #$03
	jmp     L0003
L0021:	lda     c_sp
	ldx     c_sp+1
	jsr     _sd_read_ocr
	ldy     #$08
	sta     (c_sp),y
	ldx     #$00
	lda     (c_sp),y
	bne     L0042
	lda     _sdcard_type
	beq     L0041
	lda     (c_sp,x)
	and     #$40
	beq     L003F
	lda     #$03
	jmp     L0040
L003F:	lda     #$02
L0040:	sta     _sdcard_type
L0041:	lda     #$06
	ldy     #$0D
	sta     (c_sp),y
	jmp     L0038
L0042:	lda     #$05
	jmp     L0003
L0027:	jsr     _sd_send_app
	cmp     #$02
	bcs     L0028
	lda     #$05
	ldy     #$0D
	sta     (c_sp),y
	jmp     L0043
L0028:	ldy     #$0A
	jsr     ldaxysp
	cmp     #$E8
	txa
	sbc     #$03
	bvc     L002B
	eor     #$80
L002B:	asl     a
	lda     #$00
	rol     a
	php
	ldy     #$09
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	plp
	beq     L002A
	lda     #$04
	ldy     #$0D
	sta     (c_sp),y
	jmp     L0043
L002A:	ldx     #$00
	lda     #$04
	jmp     L0003
L002D:	jsr     _sd_send_op_cond
	cmp     #$00
	bne     L002E
	lda     #$03
	ldy     #$0D
	sta     (c_sp),y
	jmp     L0043
L002E:	ldy     #$0A
	jsr     ldaxysp
	cmp     #$E8
	txa
	sbc     #$03
	bvc     L0031
	eor     #$80
L0031:	asl     a
	lda     #$00
	rol     a
	php
	ldy     #$09
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	plp
	beq     L0030
	lda     #$04
	ldy     #$0D
	sta     (c_sp),y
	jmp     L0043
L0030:	ldx     #$00
	lda     #$06
	jmp     L0003
L0033:	jsr     _sd_set_blocklen
	cmp     #$00
	bne     L0034
	lda     #$07
	ldy     #$0D
	sta     (c_sp),y
	jmp     L0043
L0034:	ldx     #$00
	lda     #$43
	jmp     L0003
L0036:	ldx     #$03
	lda     #$E8
	jsr     _spi_set_frequency_khz
	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_high
	lda     #$FF
	jsr     _spi_transfer
	ldx     #$00
	txa
L0003:	ldy     #$0E
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ sd_type (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sd_type: near

.segment	"CODE"

	ldx     #$00
	lda     _sdcard_type
	rts

.endproc

; ---------------------------------------------------------------
; const char *__near__ sd_error_string (unsigned char error_code)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sd_error_string: near

.segment	"CODE"

	jsr     pusha
	ldx     #$00
	lda     (c_sp,x)
	jeq     L0004
	cmp     #$01
	jeq     L0005
	cmp     #$02
	jeq     L0006
	cmp     #$03
	jeq     L0007
	cmp     #$04
	jeq     L0008
	cmp     #$05
	jeq     L0009
	cmp     #$06
	jeq     L000A
	cmp     #$07
	jeq     L000B
	cmp     #$08
	jeq     L000C
	cmp     #$09
	jeq     L000D
	cmp     #$0A
	jeq     L000E
	cmp     #$12
	jeq     L000F
	cmp     #$20
	jeq     L0010
	cmp     #$21
	jeq     L0011
	cmp     #$22
	jeq     L0012
	cmp     #$31
	jeq     L0013
	cmp     #$32
	jeq     L0014
	cmp     #$40
	jeq     L0015
	cmp     #$41
	jeq     L0016
	cmp     #$42
	jeq     L0017
	jmp     L0019
L0004:	lda     #<(S0001)
	ldx     #>(S0001)
	jmp     incsp1
L0005:	lda     #<(S0002)
	ldx     #>(S0002)
	jmp     incsp1
L0006:	lda     #<(S0003)
	ldx     #>(S0003)
	jmp     incsp1
L0007:	lda     #<(S0004)
	ldx     #>(S0004)
	jmp     incsp1
L0008:	lda     #<(S0005)
	ldx     #>(S0005)
	jmp     incsp1
L0009:	lda     #<(S0006)
	ldx     #>(S0006)
	jmp     incsp1
L000A:	lda     #<(S0007)
	ldx     #>(S0007)
	jmp     incsp1
L000B:	lda     #<(S0008)
	ldx     #>(S0008)
	jmp     incsp1
L000C:	lda     #<(S0009)
	ldx     #>(S0009)
	jmp     incsp1
L000D:	lda     #<(S000A)
	ldx     #>(S000A)
	jmp     incsp1
L000E:	lda     #<(S000B)
	ldx     #>(S000B)
	jmp     incsp1
L000F:	lda     #<(S000C)
	ldx     #>(S000C)
	jmp     incsp1
L0010:	lda     #<(S000D)
	ldx     #>(S000D)
	jmp     incsp1
L0011:	lda     #<(S000E)
	ldx     #>(S000E)
	jmp     incsp1
L0012:	lda     #<(S000F)
	ldx     #>(S000F)
	jmp     incsp1
L0013:	lda     #<(S0010)
	ldx     #>(S0010)
	jmp     incsp1
L0014:	lda     #<(S0011)
	ldx     #>(S0011)
	jmp     incsp1
L0015:	lda     #<(S0012)
	ldx     #>(S0012)
	jmp     incsp1
L0016:	lda     #<(S0013)
	ldx     #>(S0013)
	jmp     incsp1
L0017:	lda     #<(S0014)
	ldx     #>(S0014)
	jmp     incsp1
L0019:	txa
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ sd_crc7_byte (unsigned char crc, unsigned char data)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sd_crc7_byte: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp1
	lda     #$00
	tay
L0007:	sta     (c_sp),y
	cmp     #$08
	bcs     L0003
	ldy     #$02
	lda     (c_sp),y
	asl     a
	sta     (c_sp),y
	dey
	eor     (c_sp),y
	and     #$80
	beq     L0009
	iny
	lda     (c_sp),y
	eor     #$09
	sta     (c_sp),y
	dey
L0009:	lda     (c_sp),y
	asl     a
	sta     (c_sp),y
	dey
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0007
L0003:	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ sd_power_up (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sd_power_up: near

.segment	"CODE"

	jsr     decsp1
	lda     #$64
	jsr     pusha
	lda     #$00
	jsr     pusha
	jsr     _spi_init
	ldx     #$00
	lda     #$64
	jsr     _spi_set_frequency_khz
	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_high
	lda     #$FF
	jsr     _spi_transfer
	ldx     #$00
	lda     #$01
	jsr     _timer_delay_ms
	lda     #$00
	tay
L0006:	sta     (c_sp),y
	cmp     #$0A
	bcs     L0007
	lda     #$FF
	jsr     _spi_transfer
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0006
L0007:	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_high
	lda     #$FF
	jsr     _spi_transfer
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ sd_go_idle_state (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sd_go_idle_state: near

.segment	"CODE"

	jsr     decsp1
	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_low
	lda     #$FF
	jsr     _spi_transfer
	lda     #$00
	jsr     pusha
	jsr     pusha
	jsr     pusha
	jsr     pusha
	jsr     _sd_cmd
	ldy     #$00
	sta     (c_sp),y
	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_high
	lda     #$FF
	jsr     _spi_transfer
	ldx     #$00
	lda     (c_sp,x)
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ sd_send_if_cond (unsigned char *r7_data)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sd_send_if_cond: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp2
	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_low
	lda     #$FF
	jsr     _spi_transfer
	lda     #$08
	jsr     pusha
	lda     #$00
	jsr     pusha
	jsr     pusha
	lda     #$01
	jsr     pusha
	lda     #$AA
	jsr     _sd_cmd
	ldy     #$00
	sta     (c_sp),y
	cmp     #$01
	bne     L0008
	tya
	iny
L0007:	sta     (c_sp),y
	cmp     #$04
	bcs     L0008
	lda     (c_sp),y
	clc
	iny
	adc     (c_sp),y
	pha
	lda     #$00
	iny
	adc     (c_sp),y
	tax
	pla
	jsr     pushax
	lda     #$FF
	jsr     _spi_transfer
	ldy     #$00
	jsr     staspidx
	ldy     #$01
	clc
	tya
	adc     (c_sp),y
	jmp     L0007
L0008:	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_high
	lda     #$FF
	jsr     _spi_transfer
	ldx     #$00
	lda     (c_sp,x)
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ sd_read_ocr (unsigned char *ocr_data)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sd_read_ocr: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp2
	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_low
	lda     #$FF
	jsr     _spi_transfer
	lda     #$3A
	jsr     pusha
	lda     #$00
	jsr     pusha
	jsr     pusha
	jsr     pusha
	jsr     _sd_cmd
	ldy     #$00
	sta     (c_sp),y
	cmp     #$00
	bne     L0008
	iny
L0007:	sta     (c_sp),y
	cmp     #$04
	bcs     L0008
	lda     (c_sp),y
	clc
	iny
	adc     (c_sp),y
	pha
	lda     #$00
	iny
	adc     (c_sp),y
	tax
	pla
	jsr     pushax
	lda     #$FF
	jsr     _spi_transfer
	ldy     #$00
	jsr     staspidx
	ldy     #$01
	clc
	tya
	adc     (c_sp),y
	jmp     L0007
L0008:	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_high
	lda     #$FF
	jsr     _spi_transfer
	ldx     #$00
	lda     (c_sp,x)
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ sd_send_app (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sd_send_app: near

.segment	"CODE"

	jsr     decsp1
	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_low
	lda     #$FF
	jsr     _spi_transfer
	lda     #$37
	jsr     pusha
	lda     #$00
	jsr     pusha
	jsr     pusha
	jsr     pusha
	jsr     _sd_cmd
	ldy     #$00
	sta     (c_sp),y
	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_high
	lda     #$FF
	jsr     _spi_transfer
	ldx     #$00
	lda     (c_sp,x)
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ sd_send_op_cond (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sd_send_op_cond: near

.segment	"CODE"

	jsr     decsp1
	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_low
	lda     #$FF
	jsr     _spi_transfer
	lda     #$29
	jsr     pusha
	lda     _sdcard_type
	beq     L0005
	lda     #$40
L0005:	jsr     pusha
	lda     #$00
	jsr     pusha
	jsr     pusha
	jsr     _sd_cmd
	ldy     #$00
	sta     (c_sp),y
	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_high
	lda     #$FF
	jsr     _spi_transfer
	ldx     #$00
	lda     (c_sp,x)
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ sd_set_blocklen (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sd_set_blocklen: near

.segment	"CODE"

	jsr     decsp1
	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_low
	lda     #$FF
	jsr     _spi_transfer
	lda     #$10
	jsr     pusha
	lda     #$00
	jsr     pusha
	jsr     pusha
	lda     #$02
	jsr     pusha
	lda     #$00
	jsr     _sd_cmd
	ldy     #$00
	sta     (c_sp),y
	lda     #$FF
	jsr     _spi_transfer
	jsr     _spi_cs_high
	lda     #$FF
	jsr     _spi_transfer
	ldx     #$00
	lda     (c_sp,x)
	jmp     incsp1

.endproc

