;
; File generated by cc65 v 2.19 - Git 357f64e4e
;
	.fopt		compiler,"cc65 v 2.19 - Git 357f64e4e"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_sd_read
	.import		_sd_write
	.import		_sd_init
	.export		_disk_initialize
	.export		_disk_status
	.export		_disk_read
	.export		_disk_write
	.export		_disk_ioctl

.segment	"DATA"

_initialized:
	.byte	$00
_protected:
	.byte	$00
_nodisk:
	.byte	$01

; ---------------------------------------------------------------
; unsigned char __near__ disk_initialize (unsigned char pdrv)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_disk_initialize: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp2
	ldy     #$02
	lda     (c_sp),y
	beq     L000B
	ldx     #$00
	jmp     L0008
L000B:	dey
L0009:	sta     (c_sp),y
	ldx     #$00
	lda     (c_sp),y
	cmp     #$0A
	bcs     L0008
	jsr     _sd_init
	ldy     #$00
	sta     (c_sp),y
	lda     (c_sp),y
	bne     L0005
	sta     _nodisk
	sta     _protected
	lda     #$01
	sta     _initialized
	ldx     #$00
	txa
	jmp     incsp3
L0005:	iny
	clc
	tya
	adc     (c_sp),y
	jmp     L0009
L0008:	lda     #$01
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ disk_status (unsigned char pdrv)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_disk_status: near

.segment	"CODE"

	jsr     pusha
	ldx     #$00
	lda     (c_sp,x)
	beq     L0002
	lda     #$01
	jmp     incsp1
L0002:	lda     _nodisk
	beq     L0003
	lda     #$02
	jmp     incsp1
L0003:	lda     _protected
	beq     L0001
	lda     #$04
L0001:	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; enum $anon-enum-0014 __near__ disk_read (unsigned char pdrv, unsigned char *buff, unsigned long sector, unsigned int count)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_disk_read: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp2
	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	beq     L0002
	lda     #$04
	jmp     L0001
L0002:	lda     _initialized
	bne     L0003
	lda     #$03
	jmp     L0001
L0003:	ldy     #$03
	lda     (c_sp),y
	dey
	ora     (c_sp),y
	bne     L000A
	lda     #$04
	jmp     L0001
L000A:	txa
	jsr     stax0sp
L0005:	jsr     ldax0sp
	ldy     #$02
	cmp     (c_sp),y
	txa
	iny
	sbc     (c_sp),y
	bcs     L0006
	ldy     #$07
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$05
	jsr     ldaxysp
	jsr     axulong
	jsr     tosaddeax
	jsr     pusheax
	ldy     #$04
	lda     (c_sp),y
	tax
	lda     #$00
	jsr     shlax1
	clc
	ldy     #$0C
	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	jsr     _sd_read
	cmp     #$00
	beq     L0007
	ldx     #$00
	lda     #$01
	jmp     L0001
L0007:	tax
	lda     #$01
	jsr     addeq0sp
	jmp     L0005
L0006:	ldx     #$00
	txa
L0001:	ldy     #$0B
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; enum $anon-enum-0014 __near__ disk_write (unsigned char pdrv, const unsigned char *buff, unsigned long sector, unsigned int count)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_disk_write: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp2
	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	beq     L0002
	lda     #$04
	jmp     L0001
L0002:	lda     _initialized
	bne     L0003
	lda     #$03
	jmp     L0001
L0003:	ldy     #$03
	lda     (c_sp),y
	dey
	ora     (c_sp),y
	bne     L000A
	lda     #$04
	jmp     L0001
L000A:	txa
	jsr     stax0sp
L0005:	jsr     ldax0sp
	ldy     #$02
	cmp     (c_sp),y
	txa
	iny
	sbc     (c_sp),y
	bcs     L0006
	ldy     #$07
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$05
	jsr     ldaxysp
	jsr     axulong
	jsr     tosaddeax
	jsr     pusheax
	ldy     #$04
	lda     (c_sp),y
	tax
	lda     #$00
	jsr     shlax1
	clc
	ldy     #$0C
	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	jsr     _sd_write
	cmp     #$00
	beq     L0007
	ldx     #$00
	lda     #$01
	jmp     L0001
L0007:	tax
	lda     #$01
	jsr     addeq0sp
	jmp     L0005
L0006:	ldx     #$00
	txa
L0001:	ldy     #$0B
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; enum $anon-enum-0014 __near__ disk_ioctl (unsigned char pdrv, unsigned char cmd, void *buff)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_disk_ioctl: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp1
	ldy     #$04
	lda     (c_sp),y
	beq     L0002
	ldx     #$00
	tya
	jmp     incsp5
L0002:	lda     _initialized
	bne     L000C
	tax
	lda     #$03
	jmp     incsp5
L000C:	lda     #$01
	ldy     #$00
	sta     (c_sp),y
	ldy     #$03
	lda     (c_sp),y
	beq     L0012
	cmp     #$01
	beq     L0012
	cmp     #$02
	beq     L0008
	cmp     #$03
	beq     L0009
	jmp     L0011
L0008:	dey
	jsr     ldptr1ysp
	lda     #$00
	tay
	sta     (ptr1),y
	iny
	lda     #$02
	sta     (ptr1),y
	lda     #$00
	jmp     L0012
L0009:	iny
	jsr     pushwysp
	lda     #$00
	sta     sreg+1
	sta     sreg
	lda     #$20
	ldx     #$00
	ldy     #$00
	jsr     steaxspidx
	txa
	jmp     L0012
L0011:	lda     #$04
L0012:	ldy     #$00
	sta     (c_sp),y
	ldx     #$00
	lda     (c_sp),y
	jmp     incsp5

.endproc

