;
; File generated by cc65 v 2.19 - Git 357f64e4e
;
	.fopt		compiler,"cc65 v 2.19 - Git 357f64e4e"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_printf
	.export		_spi_init
	.export		_spi_set_divisor
	.export		_spi_set_mode
	.export		_spi_cs_low
	.export		_spi_cs_high
	.export		_spi_calculate_divisor
	.export		_spi_set_frequency_khz
	.export		_spi_transfer

.segment	"RODATA"

S0001:
	.byte	$53,$50,$49,$20,$43,$6C,$6F,$63,$6B,$3A,$20,$33,$30,$20,$4D,$48
	.byte	$7A,$2C,$20,$54,$61,$72,$67,$65,$74,$3A,$20,$25,$64,$20,$6B,$48
	.byte	$7A,$2C,$20,$44,$69,$76,$69,$73,$6F,$72,$3A,$20,$25,$64,$0A,$00

; ---------------------------------------------------------------
; void __near__ spi_init (unsigned char divisor, unsigned char cpol, unsigned char cpha)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_spi_init: near

.segment	"CODE"

	jsr     pusha
	ldy     #$02
	lda     (c_sp),y
	jsr     _spi_set_divisor
	ldy     #$01
	lda     (c_sp),y
	jsr     pusha
	ldy     #$01
	lda     (c_sp),y
	jsr     _spi_set_mode
	jsr     _spi_cs_high
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ spi_set_divisor (unsigned char divisor)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_spi_set_divisor: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (c_sp),y
	sta     $F013
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ spi_set_mode (unsigned char cpol, unsigned char cpha)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_spi_set_mode: near

.segment	"CODE"

	jsr     pusha
	lda     $F010
	and     #$03
	sta     ptr1
	ldy     #$00
	lda     (c_sp),y
	asl     a
	iny
	ora     (c_sp),y
	ora     ptr1
	sta     $F010
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ spi_cs_low (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_spi_cs_low: near

.segment	"CODE"

	lda     $F010
	ora     #$04
	sta     $F010
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ spi_cs_high (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_spi_cs_high: near

.segment	"CODE"

	lda     $F010
	and     #$FB
	sta     $F010
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ spi_calculate_divisor (unsigned int target_khz)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_spi_calculate_divisor: near

.segment	"CODE"

	jsr     pushax
	lda     #$30
	ldx     #$75
	jsr     push0ax
	jsr     decsp2
	ldy     #$05
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$0B
	jsr     ldaxysp
	jsr     shlax3
	jsr     axulong
	jsr     tosudiveax
	jsr     stax0sp
	cpx     #$80
	bcc     L0002
	ldx     #$00
	txa
	jsr     stax0sp
L0002:	jsr     ldax0sp
	cmp     #$00
	txa
	sbc     #$01
	bvs     L0004
	eor     #$80
L0004:	bpl     L0003
	ldx     #$00
	lda     #$FF
	jsr     stax0sp
L0003:	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     pushax
	ldy     #$0B
	jsr     pushwysp
	ldy     #$07
	jsr     pushwysp
	ldy     #$06
	jsr     _printf
	ldx     #$00
	lda     (c_sp,x)
	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; void __near__ spi_set_frequency_khz (unsigned int target_khz)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_spi_set_frequency_khz: near

.segment	"CODE"

	jsr     pushax
	jsr     ldax0sp
	jsr     _spi_calculate_divisor
	jsr     pusha
	ldy     #$00
	lda     (c_sp),y
	jsr     _spi_set_divisor
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ spi_transfer (unsigned char data)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_spi_transfer: near

.segment	"CODE"

	jsr     pusha
L0008:	lda     $F011
	and     #$02
	beq     L0008
	ldy     #$00
	lda     (c_sp),y
	sta     $F012
L0009:	lda     $F011
	and     #$01
	beq     L0009
	ldx     #$00
	lda     $F012
	jmp     incsp1

.endproc

